Repository lfzinho/Assistente-Amplia, pull requests merged in 2023-12, with the labels that each got.

#5 Refactor/person class structure
  src/models/BankAccount.py
  src/models/ContaBancaria.py
  src/models/PaymentMethod.py
  src/models/Person.py
  src/models/Pessoa.py
  src/models/Pix.py
  tests/test_models/test_bank_account.py
  tests/test_models/test_payment_method.py
  tests/test_models/test_person.py
  tests/test_models/test_pix.py
  tests/test_models/testa_conta_bancaria.py
  tests/test_models/testa_metodo_pagamento.py
  tests/test_models/testa_pessoa.py
  tests/test_models/testa_pix.py
Labels: enhancement

#8 Feature/beneficiary
  src/models/Beneficiary.py
  tests/test_models/test_beneficiary.py
Labels: enhancement

#9 Feature/analyst
  src/models/Analyst.py
  src/models/Person.py
  tests/test_models/test_analyst.py
  tests/test_models/test_person.py
Labels: enhancement

#10 Feature/teacher student
  src/models/Aluno.py
  src/models/Professor.py
  src/models/Student.py
  src/models/Teacher.py
  tests/test_models/test_student.py
  tests/test_models/test_teacher.py
  tests/test_models/testa_aluno.py
  tests/test_models/testa_professor.py
Labels: enhancement

#11 Feature/database bridge & interface
  .gitignore
  requirements.txt
  src/database/database.py
  src/interface/__init__.py
  src/interface/_init_path.py
  src/interface/administrator_form_classes.py
  src/interface/analyst_form_classes.py
  src/interface/beneficiary_form_classes.py
  src/interface/director_form_classes.py
  src/interface/fields.py
  src/interface/form.py
  src/interface/form_classes.py
  src/interface/index.py
  src/interface/manager_pages.py
  src/interface/pages/administrator.py
  src/interface/pages/analyst.py
  src/interface/pages/beneficiary.py
  src/interface/pages/director.py
  src/interface/pages/person.py
  src/interface/pages/student.py
  src/interface/pages/teacher.py
  src/interface/person_form_classes.py
  src/interface/student_form_classes.py
  src/interface/teacher_form_classes.py
  tests/test_interface/test_beneficiary_form_classes.py
  tests/test_interface/test_fields.py
  tests/test_interface/test_form_classes.py
Labels: enhancement

#12 Feature/cash
  src/models/Cash.py
  tests/test_models/test_cash.py
Labels: enhancement

#13 Feature/payment class
  src/models/Payment.py
  tests/test_models/test_payment.py
Labels: enhancement

#14 Feature/director
  src/models/Analyst.py
  src/models/Director.py
  tests/test_models/test_analyst.py
  tests/test_models/test_director.py
  tests/test_models/test_person.py
Labels: enhancement

#16 Feature/administrator
  src/interface/forms/form.py
  src/models/Administrator.py
  src/models/Cash.py
  src/models/Director.py
  tests/test_interface/test_fields.py
  tests/test_models/test_administrator.py
  tests/test_models/test_director.py
Labels: enhancement

#17 test/database tests
  src/database/database.py
  tests/test_database/test_database_manager.py
Labels: test, refactor

#20 feat/authentication
  src/authentication/authentication.py
  tests/test_authentication/test_autentication.py
Labels: enhancement, test

#22 Feature/presence list
  .gitignore
  src/models/PresenceList.py
  tests/test_models/test_presence_list.py
Labels: enhancement

#24 feat/authentication
  Makefile
  src/authentication/authentication.py
  src/interface/index.py
  src/interface/login.py
  src/interface/manager_pages.py
  tests/test_authentication/test_autentication.py
Labels: enhancement, test, refactor

#26 style: add docstrings
  src/models/Administrator.py
  src/models/Analyst.py
  src/models/Beneficiary.py
  src/models/Cash.py
  src/models/Director.py
  src/models/Payment.py
  src/models/PaymentMethod.py
  src/models/Pix.py
  src/models/Student.py
  src/models/Teacher.py
  tests/test_models/test_cash.py
  tests/test_models/test_payment.py
Labels: documentation

#25 Feature/payment observer
  src/models/EventListener.py
  src/models/EventManager.py
  src/models/Payment.py
  src/models/PaymentEventListener.py
  tests/test_models/test_director.py
  tests/test_models/test_event_listener.py
  tests/test_models/test_event_manager.py
  tests/test_models/test_payment.py
  tests/test_models/test_payment_event_listener.py
  tests/test_models/test_presence_list.py
Labels: enhancement

#28 Feature/especific pages
  src/interface/especific_pages.py
  src/interface/forms/fields.py
  src/interface/forms/payment_form_classes.py
  src/interface/manager_pages.py
  src/interface/pages/payment_control.py
Labels: enhancement

#29 Pull request necessário para alinhar branches
  src/interface/especific_pages.py
  src/interface/forms/fields.py
  src/interface/forms/payment_form_classes.py
  src/interface/login.py
  src/interface/manager_pages.py
  src/interface/pages/payment_control.py
Labels: enhancement

#30 feature: PaymentDAO
  src/database/DAOFactory.py
  src/database/DataAccessObject.py
  src/database/PaymentDAO.py
  src/interface/especific_pages.py
Labels: enhancement

#35 Atualiza branch
  src/database/DataAccessObject.py
  src/interface/especific_pages.py
  src/interface/forms/administrator_form_classes.py
  src/interface/forms/analyst_form_classes.py
  src/interface/forms/base_forms.py
  src/interface/forms/beneficiary_form_classes.py
  src/interface/forms/director_form_classes.py
  src/interface/forms/form.py
  src/interface/forms/payment_form_classes.py
  src/interface/forms/person_form_classes.py
  src/interface/forms/presence_list_form_classes.py
  src/interface/forms/student_form_classes.py
  src/interface/forms/teacher_form_classes.py
  src/interface/manager_pages.py
  src/interface/pages/menu.py
Labels: enhancement

#33 feat/doctests
  src/models/Payment.py
  src/models/Person.py
  src/models/PresenceList.py
Labels: test

#38 Feature/payment observer
  src/database/PaymentDAO.py
  src/exceptions/base.py
  src/models/Payment.py
  src/models/PaymentEventListener.py
  tests/test_exceptions/test_base.py
  tests/test_models/test_event_manager.py
  tests/test_models/test_payment.py
  tests/test_models/test_payment_event_listener.py
Labels: enhancement

#39 docs/tutorial no README
  README.md
Labels: enhancement
